! Test Cases for:
! Bucket:	F2003/charVal
! Sub-Bucket:	diag
charvalueattrd001.scenario
charvalueattrd002.scenario
charvalueattrd003.scenario
charvalueattrd004.scenario
charvalueattrd005.scenario
charvalueattrd006.scenario
charvalueattrd007.scenario
charvalueattrd008.scenario
charvalueattrd009.scenario
charvalueattrd010.scenario
charvalueattrd011.scenario
charvalueattrd012.scenario
charvalueattrd013.scenario
charvalueattrd014.scenario
charvalueattrd015.scenario
charvalueattrd016.scenario
