! Test Cases for:
! Bucket:	F2003
! Sub-Bucket:	asynchIO/attribute/misc
C1117asynchAttr01.scenario

asynchAttrAssocName01.scenario
asynchAttrAssocName02.scenario
asynchAttrAssocName03.scenario
asynchAttrAssocName04.scenario

asynchAttrSelectType01.scenario
asynchAttrSelectType02.scenario
asynchAttrSelectType03.scenario
asynchAttrSelectType04.scenario

derivedSubObj01.scenario

implicitDerived01.scenario
implicitIntrinsic01.scenario

scopeModule01.scenario
scopeModule02.scenario
