! Test Cases for:
! Bucket:	F2003
! Sub-Bucket:	asynchIO/statements
.im dtio/F2003.asynchIO.statements.dtio.tl
.im filePos/F2003.asynchIO.statements.filePos.tl
.im ibmext/F2003.asynchIO.statements.ibmext.tl
.im inquire/F2003.asynchIO.statements.inquire.tl
.im misc/F2003.asynchIO.statements.misc.tl
.im otherSpec/F2003.asynchIO.statements.otherSpec.tl
.im stmt/F2003.asynchIO.statements.stmt.tl
.im wait/F2003.asynchIO.statements.wait.tl
