!* Generate a file to be compared with the one generated by execute_command_line11f.f
      IMPLICIT NONE
      INTEGER :: I

      open(unit=10, file='file01')
      DO I = 1, 100
         write(10, *) I
      END DO
      close(10)
END
