#!/usr/bin/ksh

diff ffinal515a12.out $TR_SRC/ffinal515a12.vf1 > /dev/null
ret_cd1=$?

diff ffinal515a12.out $TR_SRC/ffinal515a12.vf2 > /dev/null
ret_cd2=$?

echo $ret_cd1 $ret_cd2
if [[ $ret_cd1 = 0 || $ret_cd2 = 0 ]]
then
    rm -f ffinal515a12.out
    exit 0
else
    exit 1
fi

