!*********************************************************************
!*  ===================================================================
!*
!*  DATE                       : Jun. 28, 2006
!*
!*  PRIMARY FUNCTIONS TESTED   : New Kind argumnet for existing intrinsics
!*
!*  SECONDARY FUNCTIONS TESTED : INDEX
!*
!*  REFERENCE                  : Feature Number 289083
!*
!*  REQUIRED COMPILER OPTIONS  : -qfree=f90
!*
!*  KEYWORD(S)                 :
!*  TARGET(S)                  :
!*  NUMBER OF TESTS CONDITIONS :
!*
!*  DESCRIPTION
!*
!*  Result Value.
!*  Case (iii): The value of the result 1 is zero if no character of STRING is in SET or if the
!*  length of STRING or SET is zero.
!*
!*  ()
!*
!234767890123456789012345678901234567890123456789012345678901234567890


  PROGRAM kindArgScan7

  CHARACTER(:), ALLOCATABLE :: CC(:)
  LOGICAL(1),   ALLOCATABLE :: K1(:,:)
  LOGICAL(2),   POINTER     :: K2(:,:)
  LOGICAL(4),   ALLOCATABLE :: K4(:,:)
  LOGICAL(8),   POINTER     :: K8(:,:)

  CHARACTER(3)              :: SET=ACHAR(0)//ACHAR(0)//ACHAR(0)

  ALLOCATE(CC(127), SOURCE=(/(CHAR(I)//CHAR(I)//CHAR(I)//CHAR(I)//CHAR(I)//CHAR(I)//CHAR(I), I=1, 127)/))

  ASSOCIATE (CC => CC)

! Case 1

  DO I1 = 1, 127
    IF (     SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K8))   .NE. 0)               ERROR STOP 11
    IF (KIND(SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K8)))  .NE. 8)               ERROR STOP 12
    IF (     SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K4))   .NE. 0)               ERROR STOP 13
    IF (KIND(SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K4)))  .NE. 4)               ERROR STOP 14
    IF (     SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K2))   .NE. 0)               ERROR STOP 17
    IF (KIND(SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K2)))  .NE. 2)               ERROR STOP 16
    IF (     SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K1))   .NE. 0)               ERROR STOP 17
    IF (KIND(SCAN(STRING=CC(I1), SET=SET, KIND=KIND(K1)))  .NE. 1)               ERROR STOP 18
  END DO


  DO I4 = 1, 127
    IF (     SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K8))   .NE. 0)               ERROR STOP 21
    IF (KIND(SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)               ERROR STOP 22
    IF (     SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K4))   .NE. 0)               ERROR STOP 23
    IF (KIND(SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)               ERROR STOP 24
    IF (     SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K2))   .NE. 0)               ERROR STOP 27
    IF (KIND(SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)               ERROR STOP 26
    IF (     SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K1))   .NE. 0)               ERROR STOP 27
    IF (KIND(SCAN(STRING=CC(I4), SET=SET, BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)               ERROR STOP 28
  END DO


  IF (ANY( SCAN(STRING=CC, SET=SET, KIND=KIND(K8))   .NE. 0))           ERROR STOP 31
  IF (KIND(SCAN(STRING=CC, SET=SET, KIND=KIND(K8)))  .NE. 8)            ERROR STOP 32
  IF (ANY( SCAN(STRING=CC, SET=SET, KIND=KIND(K4))   .NE. 0))           ERROR STOP 33
  IF (KIND(SCAN(STRING=CC, SET=SET, KIND=KIND(K4)))  .NE. 4)            ERROR STOP 34
  IF (ANY( SCAN(STRING=CC, SET=SET, KIND=KIND(K2))   .NE. 0))           ERROR STOP 35
  IF (KIND(SCAN(STRING=CC, SET=SET, KIND=KIND(K2)))  .NE. 2)            ERROR STOP 36
  IF (ANY( SCAN(STRING=CC, SET=SET, KIND=KIND(K1))   .NE. 0))           ERROR STOP 37
  IF (KIND(SCAN(STRING=CC, SET=SET, KIND=KIND(K1)))  .NE. 1)            ERROR STOP 38

  IF (ANY( SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K8))   .NE. 0))         ERROR STOP 41
  IF (KIND(SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)          ERROR STOP 42
  IF (ANY( SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K4))   .NE. 0))         ERROR STOP 43
  IF (KIND(SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)          ERROR STOP 44
  IF (ANY( SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K2))   .NE. 0))         ERROR STOP 47
  IF (KIND(SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)          ERROR STOP 46
  IF (ANY( SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K1))   .NE. 0))         ERROR STOP 47
  IF (KIND(SCAN(STRING=CC, SET=SET, BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)          ERROR STOP 48

! case 2
  DO I1 = 1, 127
    IF (     SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K8))   .NE. 0)               ERROR STOP 51
    IF (KIND(SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K8)))  .NE. 8)               ERROR STOP 52
    IF (     SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K4))   .NE. 0)               ERROR STOP 53
    IF (KIND(SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K4)))  .NE. 4)               ERROR STOP 54
    IF (     SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K2))   .NE. 0)               ERROR STOP 57
    IF (KIND(SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K2)))  .NE. 2)               ERROR STOP 56
    IF (     SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K1))   .NE. 0)               ERROR STOP 57
    IF (KIND(SCAN(STRING=CC(I1), SET=SET(1:0), KIND=KIND(K1)))  .NE. 1)               ERROR STOP 58
  END DO


  DO I4 = 1, 127
    IF (     SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K8))   .NE. 0)               ERROR STOP 61
    IF (KIND(SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)               ERROR STOP 62
    IF (     SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K4))   .NE. 0)               ERROR STOP 63
    IF (KIND(SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)               ERROR STOP 64
    IF (     SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K2))   .NE. 0)               ERROR STOP 67
    IF (KIND(SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)               ERROR STOP 66
    IF (     SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K1))   .NE. 0)               ERROR STOP 67
    IF (KIND(SCAN(STRING=CC(I4), SET=SET(1:0), BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)               ERROR STOP 68
  END DO


  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K8))   .NE. 0))           ERROR STOP 71
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K8)))  .NE. 8)            ERROR STOP 72
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K4))   .NE. 0))           ERROR STOP 73
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K4)))  .NE. 4)            ERROR STOP 74
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K2))   .NE. 0))           ERROR STOP 75
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K2)))  .NE. 2)            ERROR STOP 76
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K1))   .NE. 0))           ERROR STOP 77
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), KIND=KIND(K1)))  .NE. 1)            ERROR STOP 78

  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K8))   .NE. 0))         ERROR STOP 81
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)          ERROR STOP 82
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K4))   .NE. 0))         ERROR STOP 83
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)          ERROR STOP 84
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K2))   .NE. 0))         ERROR STOP 87
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)          ERROR STOP 86
  IF (ANY( SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K1))   .NE. 0))         ERROR STOP 87
  IF (KIND(SCAN(STRING=CC, SET=SET(1:0), BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)          ERROR STOP 88

! Case 3

  DO I1 = 1, 127
    IF (     SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K8))   .NE. 0)               ERROR STOP 111
    IF (KIND(SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K8)))  .NE. 8)               ERROR STOP 112
    IF (     SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K4))   .NE. 0)               ERROR STOP 113
    IF (KIND(SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K4)))  .NE. 4)               ERROR STOP 114
    IF (     SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K2))   .NE. 0)               ERROR STOP 117
    IF (KIND(SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K2)))  .NE. 2)               ERROR STOP 116
    IF (     SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K1))   .NE. 0)               ERROR STOP 117
    IF (KIND(SCAN(STRING=CC(I1)(1:0), SET=SET, KIND=KIND(K1)))  .NE. 1)               ERROR STOP 118
  END DO


  DO I4 = 1, 127
    IF (     SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K8))   .NE. 0)               ERROR STOP 121
    IF (KIND(SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)               ERROR STOP 122
    IF (     SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K4))   .NE. 0)               ERROR STOP 123
    IF (KIND(SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)               ERROR STOP 124
    IF (     SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K2))   .NE. 0)               ERROR STOP 127
    IF (KIND(SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)               ERROR STOP 126
    IF (     SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K1))   .NE. 0)               ERROR STOP 127
    IF (KIND(SCAN(STRING=CC(I4)(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)               ERROR STOP 128
  END DO


  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K8))   .NE. 0))           ERROR STOP 131
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K8)))  .NE. 8)            ERROR STOP 132
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K4))   .NE. 0))           ERROR STOP 133
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K4)))  .NE. 4)            ERROR STOP 134
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K2))   .NE. 0))           ERROR STOP 135
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K2)))  .NE. 2)            ERROR STOP 136
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K1))   .NE. 0))           ERROR STOP 137
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, KIND=KIND(K1)))  .NE. 1)            ERROR STOP 138

  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K8))   .NE. 0))         ERROR STOP 141
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K8)))  .NE. 8)          ERROR STOP 142
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K4))   .NE. 0))         ERROR STOP 143
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K4)))  .NE. 4)          ERROR STOP 144
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K2))   .NE. 0))         ERROR STOP 147
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K2)))  .NE. 2)          ERROR STOP 146
  IF (ANY( SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K1))   .NE. 0))         ERROR STOP 147
  IF (KIND(SCAN(STRING=CC(1:0), SET=SET, BACK=.FALSE., KIND=KIND(K1)))  .NE. 1)          ERROR STOP 148


  END ASSOCIATE

  END

